### ISSUE TITLE
changing config.js path in index.html

### ISSUE THREAD

**Issue by ryanCchen** [pivotal-cf/pui-react-tools#14]
I was wondering if there is currently a way to modify the src path for config.js in index.html? The way my app is being deployed requires this.

**Comment by charleshansen** [comment]
It is currently hard-coded to '/config.js'.

On the plus side, you can create your own config file relatively simply using the `config` object provided by pui-react-tools (see https://github.com/pivotal-cf/react-starter/blob/master/server/app.js#L16). You can name that file whatever you want or serve it wherever you want. If you are using express, you can copy the pattern in react-starter directly. Otherwise, the best plan may be to write a gulp task that calls `Assets.tasks.assetsConfig` and pipes the output into a different folder than `public` and/or renames it.

Unfortunately, the html will still look for '/config.js' and it won't be there, but it won't cause any issues. I could add an option to turn this off, but it will be a little clunky.

As a too-much-work last option, you can provide your own Layout. The default Layout renders the script tags, so you can change it there. You shouldn't have to do it this way though.

**Comment by ryanCchen** [comment]
Thanks @charleshansen! The current config file works well, it is just the path on the script tag which is why I am leaning towards adding/modifying the layout.js file.

**Comment by ryanCchen** [comment]
Is it bad to have it change based off node_env? for example, production I will modify the path name, but development will keep it to default.
