### ISSUE TITLE
jasmine task fails silently when require bypasses loaders

### ISSUE THREAD

**Issue by atomanyih** [pivotal-cf/pui-react-tools#19]
on our project we had to pull in a library that wasn't available on npm

we wanted to bypass babel when requiring it because it's slow and doesn't need to be transpiled

`const headtrackr = require('!../vendor/headtrackr');`

somehow this causes `gulp spec-app` to lose track of all our tests:

```
[14:18:52] Starting 'spec-app'...
[14:18:59] Jasmine server listening on port 8889

0 specs, 0 failures
Finished in 3.5 seconds
[14:19:03] Finished 'spec-app' after 11 s
```

**Comment by charleshansen** [comment]
Ugh, looks like a bug in entry-loader. I didn't know about the bypassing options when I wrote it. I'll take a look.

**Comment by charleshansen** [comment]
Turns out this is a really gross bug. 

There is an issue in entry-loader that is related to this open webpack issue: https://github.com/webpack/webpack/issues/667

I think I can fix this by adding a webpack plugin to support the loader, but this only partially solves your problem. If you ever want to do server-side rendering, node will crash on the '!'. 

I think you just shouldn't use the '!' webpack syntax for anything that runs at compile time for your app. If you put it inside of a `componentDidMount` or something, it should be fine.

There are two alternate solutions for you:

- Modify your webpack config so to add an `exclude` to the babel loader to exclude `headtrackr`. This is kind gross because you have to replace some of the webpack config you get from PUI React Tools.

- Modify webpack config to make `headtrackr` an [external](https://webpack.github.io/docs/library-and-externals.html). This is a purely additive change to the webpack config, so should be much easier. You would need to serve the file yourself in production. You may also want to make the whole vendor directory an external, there is a [plugin](https://www.npmjs.com/package/webpack-externals-plugin) for that

**Comment by atomanyih** [comment]
@charleshansen thanks for the response!

The project just ended but I think we just excluded the `vendor` directory when building the app for prod and dev. In test it just shows a warning when trying to babel a big ole library in a single file

**Comment by rdy** [comment]
@atomanyih i might have a solution for you in the future using the DllReference plugin

**Comment by charleshansen** [comment]
entry-loader isn't a thing anymore, closing
