### ISSUE TITLE
Use of React Hot Loader 3 breaks async functions

### ISSUE THREAD

**Issue by JeffreyATW** [pivotal-cf/pui-react-tools#23]
I upgraded pui-react-tools from 2.0.2 to 2.0.3, but the slight change from RHL 1 to 3 caused my async functions to stop working.

Under the hood, this bug is at fault: https://github.com/gaearon/react-hot-loader/issues/391

I would recommend reverting, not to 1.3.0, but to 1.3.1, which solves the ReactMount issue that was the reason pui-react-tools upgraded to RHL 3 in the first place.

**Comment by charleshansen** [comment]
Thanks for the detailed fix suggestion. Yeah, the hot loader broke. There is a better fix using the react-hot-loader babel plugin, but it involves changing code not under the control of pui-react-tools. I'll try to find a way to get that in, but if that takes too long, I'll at least try your 1.3.1 lock.

**Comment by rdy** [comment]
I will generate a new version that downgrades the hot module loader for a version 2, but we're probably going to move forward with the newer hot module loader (beta 3) in a major rev since it is so different. At the time we were forced to upgrade because there wasn't a clear fix and it was breaking multiple projects.
