### ISSUE TITLE
Allow for more granular control of minification and watching-for-changes of assets task

### ISSUE THREAD

**Issue by rkawala** [pivotal-cf/pui-react-tools#31]
We're trying to evolve an incremental compilation setup that works well with a Spring backend. To do what we want, we need to be able to specify two new Assets options. The first would let us say "Set watch to false so that Webpack doesn't block waiting for new changes." The second would let us say "Prettify the source rather than minifying it."

Would you be open to this? If so, we can submit a pull request for your comments. Our first thought is to have flags like "neverWatch=true" and "prettify=true". The former would override the use of isDevelopment() for the watch value. The latter would override the use of isProduction() for deciding which pipe is returned by the assets() function.

Thanks,
Rick

**Comment by charleshansen** [comment]
Hey Rick,

My understanding is that your issue is being handled by @rdy out of band and there is a better solution than the PR. If you still need more support for this, let me know. I am in principle open to a PR to add options for Spring asset flows. We are slowly trying to work out a more transparent version of pui-react-tools where you can just do this stuff yourself, but no guarantees on a timeline.

**Comment by rdy** [comment]
Let me know if there is some better long term solution we can work out, otherwise our next version which allow more custom webpack should take care of making this easier.

**Comment by rkawala** [comment]
With help from @rdy, I managed to work out a solution, so let's leave this closed.
